import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View, useWindowDimensions } from "react-native";

type AISuggestListScreenProps = {};

export default function AISuggestListScreen({}: AISuggestListScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center justify-between"><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[#0A7A36] text-[32px] font-bold">Gợi ý từ AI</Text></View><Feather name="sliders" size={18} color="#4A534C" /></View><Text className="mt-6 text-[#7A827B] tracking-[2px]">PHÂN TÍCH THÀNH CÔNG</Text><Text className="mt-2 text-[#1E2420] text-[56px] leading-[58px] font-extrabold">Dựa trên tủ lạnh của bạn, AI gợi ý...</Text><View className="mt-3 flex-row gap-2">{['Cà chua','Trứng','Hành tây','+2 khác'].map((x,i)=><View key={x} className={`px-4 py-2 rounded-full ${i<3?'bg-[#92E18A]':'bg-[#DDE3DA]'}`}><Text>{x}</Text></View>)}</View>{['Trứng sốt cà chua kiểu Ý','Trứng cuộn rau củ','Salad Trứng & Cà chua bi'].map((x,i)=><View key={x} className="mt-5 rounded-[28px] bg-[#F4F5F2] overflow-hidden"><Image source={{uri:["https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&q=80","https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80"][i]}} className="h-[220px] w-full" /><View className="p-5"><View className="flex-row justify-between"><Text className="text-[#1E2420] text-[40px] leading-[42px] font-bold flex-1">{x}</Text><Text className="text-[#0A7A36] font-bold">{i===2?'HEALTHY':'Dễ'}</Text></View><Text className="mt-2 text-[#4A534C]">⏱ {15-i*3} phút   ⚡ {320-i*20} kcal</Text><TouchableOpacity className="mt-4 rounded-full bg-[#0A7A36] py-4 items-center"><Text className="text-white font-bold">Xem công thức →</Text></TouchableOpacity></View></View>)}</ScrollView></View></SafeAreaView>;
}
