import React from "react";
import { Feather } from "@expo/vector-icons";
import { Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View, useWindowDimensions } from "react-native";

type FilterScreenProps = { onApply: () => void; };

export default function FilterScreen({ onApply }: FilterScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center justify-between"><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[#0A7A36] text-[32px] font-bold">Bộ lọc tìm kiếm</Text></View><Text>Đặt lại</Text></View><Text className="mt-6 text-[#1E2420] text-[58px] leading-[60px] font-extrabold">Tinh chỉnh khẩu vị của bạn</Text><Text className="mt-3 text-[#4A534C]">Tìm công thức hoàn hảo dựa trên nhu cầu cá nhân.</Text><Text className="mt-6 text-[36px] font-bold">Thời gian nấu</Text><View className="mt-3 flex-row flex-wrap gap-3">{['Dưới 15 phút','15 - 30 phút','30 - 60 phút','Trên 1 tiếng'].map((x,i)=><View key={x} className={`px-5 py-3 rounded-full ${i===0?'bg-[#92E18A]':'bg-[#DDE3DA]'}`}><Text className="font-bold">{x}</Text></View>)}</View><Text className="mt-6 text-[36px] font-bold">Mục tiêu dinh dưỡng</Text><View className="mt-3 flex-row flex-wrap gap-2">{['Ít Carb','Giàu Protein','Keto','Chay','Dưới 500 kcal'].map((x,i)=><View key={x} className={`px-4 py-2 rounded-full ${i===0?'bg-[#92E18A]':'bg-[#DDE3DA]'}`}><Text>{x}</Text></View>)}</View><TouchableOpacity onPress={onApply} className="mt-8 rounded-full bg-[#0A7A36] py-5 items-center"><Text className="text-white text-[18px] font-bold">Áp dụng (124 kết quả)</Text></TouchableOpacity></ScrollView></View></SafeAreaView>;
}
