import React from "react";
import { Feather } from "@expo/vector-icons";
import { Platform, SafeAreaView, ScrollView, Text, TextInput, TouchableOpacity, View, useWindowDimensions } from "react-native";

type IngredientInputScreenProps = { onContinue: () => void; onOpenFilter: () => void; onOpenCamera: () => void; };

export default function IngredientInputScreen({ onContinue, onOpenFilter, onOpenCamera }: IngredientInputScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[#0A7A36] text-[32px] font-bold">Quét nguyên liệu</Text></View><Text className="mt-8 text-[#1E2420] text-[58px] leading-[60px] font-extrabold">Bạn có gì trong bếp?</Text><Text className="mt-3 text-[#4A534C] text-[17px] leading-8">Nhập những nguyên liệu bạn đang có, Culina sẽ gợi ý món ăn hoàn hảo.</Text><View className="mt-8 rounded-[24px] bg-[#E2E7DF] px-4 py-3 flex-row items-center"><Feather name="search" size={18} color="#7D857E" /><TextInput placeholder="Thêm nhanh nguyên liệu..." placeholderTextColor="#A0A8A1" className="ml-3 flex-1" /><TouchableOpacity className="rounded-full bg-[#0A7A36] px-5 py-2"><Text className="text-white font-bold">Thêm</Text></TouchableOpacity></View><View className="mt-4 flex-row flex-wrap gap-2">{['Thịt gà','Nấm hương','Gừng'].map(x=><View key={x} className="px-4 py-2 rounded-full bg-[#92E18A]"><Text className="font-bold">{x} ✕</Text></View>)}</View><View className="mt-8 flex-row justify-between items-center"><Text className="text-[#1E2420] text-[42px] font-bold">Gợi ý phổ biến</Text><TouchableOpacity onPress={onOpenFilter}><Text className="text-[#0A7A36] text-[18px] font-bold">Bộ lọc</Text></TouchableOpacity></View><View className="mt-3 flex-row flex-wrap gap-3">{['Cà chua','Trứng','Thịt bò','Hành tây','Cà rốt','Tỏi'].map(x=><View key={x} className="w-[46%] rounded-[20px] bg-[#F4F5F2] p-4 items-center"><Text className="text-[34px]">🥕</Text><Text className="mt-2 text-[18px]">{x}</Text></View>)}</View><TouchableOpacity onPress={onOpenCamera} className="mt-6 rounded-[20px] bg-[#C6E7C3] p-5"><Text className="text-[#2C7A41]">✦ Mẹo nhỏ từ Chef: Bạn có thể chụp ảnh tủ lạnh để AI nhận diện nhanh hơn!</Text></TouchableOpacity><TouchableOpacity onPress={onContinue} className="mt-6 rounded-full bg-[#0A7A36] py-5 items-center"><Text className="text-white text-[18px] font-bold">Tiếp tục</Text></TouchableOpacity></ScrollView></View></SafeAreaView>;
}
