import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View, useWindowDimensions } from "react-native";

type IngredientsListScreenProps = {};

export default function IngredientsListScreen({}: IngredientsListScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center justify-between"><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[#0A7A36] text-[32px] font-bold">Nguyên liệu</Text></View><Feather name="share-2" size={20} color="#0A7A36" /></View><Image source={{uri:"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80"}} className="mt-5 h-[320px] w-full rounded-[28px]" /><Text className="mt-6 text-[#1E2420] text-[58px] leading-[60px] font-extrabold">Salad Cá Hồi Na Uy</Text><Text className="text-[#4A534C] mt-2">⏱ 15 phút   🔥 320 kcal</Text><View className="mt-6 flex-row justify-between items-center"><Text className="text-[#1E2420] text-[44px] font-bold">Thành phần chi tiết</Text><Text className="text-[#0A7A36] text-[20px] font-bold">Dành cho 2 người ăn</Text></View>{[['Cá hồi Na Uy','200g'],['Xà lách thủy canh','100g'],['Cà chua bi','50g'],['Bơ sáp','1/2 quả'],['Sốt Olive Lemon','30ml']].map(x=><View key={x[0]} className="mt-3 rounded-[24px] bg-[#F4F5F2] p-4 flex-row justify-between items-center"><Text className="text-[30px] font-bold">{x[0]}</Text><Text className="text-[#0A7A36] text-[30px] font-bold">{x[1]}</Text></View>)}<View className="mt-6 rounded-[24px] bg-[#BCE5BE] p-5"><Text className="text-[#2E7142] font-bold">✦ CHEF AI GỢI Ý</Text><Text className="mt-2 text-[#2E7142]">Bạn có thể thêm 10g hạt điều rang để tăng vị béo bùi.</Text></View><View className="mt-6 flex-row gap-3"><TouchableOpacity className="flex-1 rounded-full border border-[#0A7A36] py-4 items-center"><Text className="text-[#0A7A36] font-bold">Danh sách mua</Text></TouchableOpacity><TouchableOpacity className="flex-1 rounded-full bg-[#0A7A36] py-4 items-center"><Text className="text-white font-bold">Thêm vào giỏ hàng</Text></TouchableOpacity></View></ScrollView></View></SafeAreaView>;
}
