import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, View, useWindowDimensions } from "react-native";

type NutritionValueScreenProps = {};

export default function NutritionValueScreen({}: NutritionValueScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center justify-between"><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[#0A7A36] text-[30px] font-bold">Chi tiết dinh dưỡng</Text></View><Feather name="heart" size={18} color="#0A7A36" /></View><Text className="mt-4 text-[#1E2420] text-[56px] leading-[58px] font-extrabold">Salad Cá Hồi Na Uy</Text><Image source={{uri:"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80"}} className="mt-5 h-[220px] w-full rounded-[26px]" /><View className="mt-5 rounded-[24px] bg-[#D7ECD5] p-5"><Text className="text-[#0A7A36]">TỔNG NĂNG LƯỢNG</Text><Text className="text-[#0A7A36] text-[60px] font-extrabold">485 kcal</Text></View>{[['Chất đạm','32g'],['Tinh bột','18g'],['Chất béo','24g']].map(x=><View key={x[0]} className="mt-3 rounded-[18px] bg-[#F4F5F2] p-4"><View className="flex-row justify-between"><Text className="font-bold">{x[0]}</Text><Text className="font-bold text-[#0A7A36]">{x[1]}</Text></View><View className="mt-2 h-2 rounded-full bg-[#DDE3DA]"><View className="h-full w-[60%] bg-[#0A7A36] rounded-full" /></View></View>)}<Text className="mt-6 text-[#1E2420] text-[40px] font-bold">Gợi ý kết hợp cùng</Text><Image source={{uri:"https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80"}} className="mt-3 h-[140px] w-full rounded-[20px]" /><Text className="mt-2 text-[30px] font-bold">Nước ép xanh thanh lọc</Text></ScrollView></View></SafeAreaView>;
}
