import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View, useWindowDimensions } from "react-native";

type RecipeOverviewScreenProps = {
  onOpenIngredients: () => void;
  onOpenNutrition: () => void;
  onOpenReviews: () => void;
  onOpenShare: () => void;
  onOpenSaved: () => void;
};

export default function RecipeOverviewScreen({ onOpenIngredients, onOpenNutrition, onOpenReviews, onOpenShare, onOpenSaved }: RecipeOverviewScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{paddingBottom:24}}><View className="px-6 pt-6 flex-row justify-between"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="text-[34px] font-bold">CHEF AI</Text><TouchableOpacity onPress={onOpenSaved}><Feather name="heart" size={20} color="#0A7A36" /></TouchableOpacity></View><Image source={{uri:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80"}} className="h-[300px] w-full mt-4" /><View className="mx-6 -mt-6 rounded-[30px] bg-[#F4F5F2] p-6"><Text className="text-[#1E2420] text-[56px] leading-[58px] font-extrabold">Salad Cá Hồi Na Uy</Text><View className="mt-3 rounded-full bg-[#DDE3DA] px-4 py-2 self-start"><Text className="text-[30px] font-bold">⭐ 4.9 <Text className="text-[16px] font-normal">(120 đánh giá)</Text></Text></View><View className="mt-6 flex-row gap-3"><View className="flex-1 rounded-[20px] bg-[#E3E7E1] p-4 items-center"><Text>THỜI GIAN</Text><Text className="text-[30px] font-bold">25 phút</Text></View><View className="flex-1 rounded-[20px] bg-[#E3E7E1] p-4 items-center"><Text>ĐỘ KHÓ</Text><Text className="text-[30px] font-bold">Dễ</Text></View></View><Text className="mt-6 text-[#1E2420] text-[42px] font-bold">Giới thiệu món ăn</Text><Text className="mt-3 text-[#3F493F] leading-8">Trải nghiệm hương vị tươi mát của biển cả Na Uy với món salad tinh tế này.</Text><Text className="mt-6 text-[#1E2420] text-[42px] font-bold">Nguyên liệu chính</Text>{['Cá hồi Na Uy (300g)','Xà lách hỗn hợp','Bơ sáp','Sốt chanh dây'].map(x=><View key={x} className="mt-2 rounded-full bg-[#DDE3DA] px-4 py-2 self-start"><Text>{x}</Text></View>)}<View className="mt-8 gap-3"><TouchableOpacity onPress={onOpenIngredients} className="rounded-full bg-[#0A7A36] py-4 items-center"><Text className="text-white text-[18px] font-bold">Danh sách nguyên liệu</Text></TouchableOpacity><TouchableOpacity onPress={onOpenNutrition} className="rounded-full bg-[#0A7A36] py-4 items-center"><Text className="text-white text-[18px] font-bold">Giá trị dinh dưỡng</Text></TouchableOpacity><TouchableOpacity onPress={onOpenReviews} className="rounded-full bg-[#0A7A36] py-4 items-center"><Text className="text-white text-[18px] font-bold">Đánh giá & nhận xét</Text></TouchableOpacity><TouchableOpacity onPress={onOpenShare} className="rounded-full bg-[#0A7A36] py-4 items-center"><Text className="text-white text-[18px] font-bold">Chia sẻ món ăn</Text></TouchableOpacity></View></View></ScrollView></View></SafeAreaView>;
}
