import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View, useWindowDimensions } from "react-native";

type ReviewsScreenProps = {};

export default function ReviewsScreen({}: ReviewsScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center justify-between"><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-3 text-[#0A7A36] text-[30px] font-bold">Salad Cá Hồi Na Uy</Text></View><Feather name="heart" size={18} color="#0A7A36" /></View><Image source={{uri:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80"}} className="mt-5 h-[260px] w-full rounded-[28px]" /><Text className="mt-5 text-[#2E7142] tracking-[3px]">ĐÁNH GIÁ & NHẬN XÉT</Text><Text className="mt-2 text-[#1E2420] text-[56px] leading-[58px] font-extrabold">Cảm nhận từ Bếp gia đình</Text><View className="mt-5 flex-row items-end"><Text className="text-[#1E2420] text-[72px] font-extrabold">4.8</Text><Text className="ml-3 text-[#4A534C]">Dựa trên 128 đánh giá</Text></View><View className="mt-4 flex-row gap-2">{['Mùi nhất','Có hình ảnh','5 sao'].map((x,i)=><View key={x} className={`px-4 py-2 rounded-full ${i===0?'bg-[#BEE3BC]':'bg-[#F4F5F2]'}`}><Text>{x}</Text></View>)}</View><View className="mt-5 rounded-[24px] bg-[#F4F5F2] p-5"><View className="flex-row items-center"><Image source={{uri:"https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&w=200&q=80"}} className="h-12 w-12 rounded-full" /><View className="ml-3"><Text className="text-[26px] font-bold">Minh Anh Lê</Text><Text className="text-[#6A726C]">★★★★★</Text></View></View><Text className="mt-3 text-[#2D342F] leading-8">Công thức cực kỳ chi tiết và dễ làm. Cá hồi áp chảo vừa chín tới...</Text></View><TouchableOpacity className="mt-6 rounded-full bg-[#0A7A36] py-4 items-center"><Text className="text-white font-bold">Xem thêm / Viết đánh giá</Text></TouchableOpacity></ScrollView></View></SafeAreaView>;
}
