import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, TextInput, TouchableOpacity, View, useWindowDimensions } from "react-native";

type SavedRecipesScreenProps = {};

export default function SavedRecipesScreen({}: SavedRecipesScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center justify-between"><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[#0A7A36] text-[32px] font-bold">Lưu món</Text></View><Feather name="heart" size={18} color="#0A7A36" /></View><Text className="mt-6 text-[#1E2420] text-[62px] leading-[64px] font-extrabold">Công thức đã lưu</Text><Text className="mt-2 text-[#4A534C]">Nơi lưu giữ những tinh hoa ẩm thực bạn yêu thích.</Text><View className="mt-4 rounded-full bg-[#DDE3DA] px-4 py-3 flex-row items-center"><Feather name="search" size={18} color="#717971" /><TextInput placeholder="Tìm kiếm trong danh sách lưu..." placeholderTextColor="#9CA49D" className="ml-3 flex-1" /></View><View className="mt-4 flex-row gap-2">{['Tất cả','Món mặn','Món chay'].map((x,i)=><View key={x} className={`px-4 py-2 rounded-full ${i===0?'bg-[#92E18A]':'bg-[#DDE3DA]'}`}><Text>{x}</Text></View>)}</View>{['Salad cá hồi & Quinoa','Tart Việt Quất','Buddha Bowl Thần Thánh'].map(x=><View key={x} className="mt-5 rounded-[24px] bg-[#F4F5F2] overflow-hidden"><Image source={{uri:"https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&q=80"}} className="h-[220px] w-full" /><View className="p-4"><Text className="text-[#1E2420] text-[38px] leading-[40px] font-extrabold">{x}</Text><Text className="mt-2 text-[#4A534C]">⏱ 30 phút</Text></View></View>)}<View className="mt-6 items-center"><Text className="text-[#4A534C]">Bạn muốn thêm món mới?</Text><Text className="text-[#0A7A36] font-bold mt-2">Khám phá kho công thức →</Text></View></ScrollView></View></SafeAreaView>;
}
