import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View, useWindowDimensions } from "react-native";

type ScanResultScreenProps = { onCreateRecipe: () => void; };

export default function ScanResultScreen({ onCreateRecipe }: ScanResultScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[#0A7A36] text-[32px] font-bold">Quét nguyên liệu</Text></View><View className="items-center mt-6"><View className="h-24 w-24 rounded-full bg-[#BDE6BC] items-center justify-center"><Text className="text-[42px]">✦</Text></View><Text className="mt-5 text-[#1E2420] text-[54px] text-center font-extrabold">Đã nhận diện xong!</Text><Text className="mt-2 text-[#4A534C] text-center">AI đã tìm thấy 5 thành phần.</Text></View>{['Cá hồi Na Uy','Măng tây','Chanh vàng','Rau mùi tây'].map(x=><View key={x} className="mt-4 rounded-[24px] bg-[#F4F5F2] p-4 flex-row items-center justify-between"><View className="flex-row items-center"><Image source={{uri:"https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=200&q=80"}} className="h-16 w-16 rounded-full" /><Text className="ml-3 text-[26px] font-bold">{x}</Text></View><View className="h-8 w-8 rounded-lg bg-[#0A7A36] items-center justify-center"><Feather name="check" size={16} color="#fff" /></View></View>)}<TouchableOpacity className="mt-5 rounded-[20px] border border-dashed border-[#AFC1AE] py-4 items-center"><Text className="text-[#4A534C]">+ Thêm nguyên liệu khác</Text></TouchableOpacity><View className="mt-5 rounded-[22px] bg-[#D9EFD7] p-4"><Text className="text-[#2D7A44]">💡 Gợi ý từ Chef AI: với nguyên liệu này, bạn có thể thực hiện món Cá hồi áp chảo sốt bơ chanh.</Text></View><TouchableOpacity onPress={onCreateRecipe} className="mt-6 rounded-full bg-[#0A7A36] py-5 items-center"><Text className="text-white text-[18px] font-bold">Tạo công thức ngay</Text></TouchableOpacity></ScrollView></View></SafeAreaView>;
}
