import React from "react";
import { Feather } from "@expo/vector-icons";
import { Image, Platform, SafeAreaView, ScrollView, Text, TouchableOpacity, View, useWindowDimensions } from "react-native";

type ShareRecipeScreenProps = {};

export default function ShareRecipeScreen({}: ShareRecipeScreenProps) {
  const isWeb = Platform.OS === "web"; const { height } = useWindowDimensions(); const webFrameHeight = Math.min(930, Math.max(760, height - 20));
  return <SafeAreaView className={isWeb?"flex-1 bg-[#ECEFED] items-center justify-center p-2":"flex-1 bg-[#ECEFED]"}><View className={isWeb?"w-[390px] bg-[#ECEFED] border border-[#BFC7D3]":"flex-1 w-full bg-[#ECEFED]"} style={isWeb?{height:webFrameHeight,borderRadius:14,overflow:"hidden"}:undefined}><ScrollView contentContainerStyle={{padding:20,paddingBottom:30}}><View className="flex-row items-center justify-between"><View className="flex-row items-center"><Feather name="arrow-left" size={20} color="#0A7A36" /><Text className="ml-4 text-[38px] font-bold">CHEF AI</Text></View><Feather name="heart" size={20} color="#0A7A36" /></View><Text className="mt-6 text-[#1E2420] text-[58px] leading-[60px] font-extrabold">Chia sẻ công thức</Text><Text className="mt-2 text-[#4A534C] text-[17px]">Lan tỏa cảm hứng nấu ăn cùng bạn bè.</Text><View className="mt-5 rounded-[28px] bg-[#F4F5F2] p-5"><Image source={{uri:"https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80"}} className="h-[260px] w-full rounded-[24px]" /><Text className="mt-4 text-[#1E2420] text-[48px] leading-[50px] font-extrabold">Salad Cá Hồi Na Uy</Text><Text className="mt-2 text-[#4A534C]">⏱ 15 phút   🔥 320 kcal</Text></View><View className="mt-6 rounded-[24px] bg-[#F4F5F2] p-5"><Text className="tracking-[4px] text-[#4A534C]">GỬI QUA ỨNG DỤNG</Text><View className="mt-4 flex-row justify-between">{['Messenger','Facebook','Zalo','Instagram'].map(x=><View key={x} className="items-center"><View className="h-12 w-12 rounded-xl bg-[#1D76E8]" /><Text className="mt-2 text-[12px]">{x}</Text></View>)}</View><Text className="tracking-[4px] text-[#4A534C] mt-6">THAO TÁC NHANH</Text>{['Sao chép liên kết','Lưu hình ảnh chia sẻ','Gửi qua Email'].map(x=><TouchableOpacity key={x} className="mt-3 rounded-full bg-[#DDE3DA] py-3 px-4"><Text>{x}</Text></TouchableOpacity>)}</View></ScrollView></View></SafeAreaView>;
}
